# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

title: Pahadi-Programmer
email: pahadiprogrammer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Talks about Software Development, management.
  Motive is to help budding as well expereicned programmers by sharing insights gained
  through day to day activities - Gathering business requirements, Feature scoping, Estimation, Design(HLD, LLD),
  Feature Developments, Code, Cr Reviews, Deployment, Feature release
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  pahadiprogrammer

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




#This is the base Jekyll theme. You can find out more info about customizing your Jekyll theme, as well as basic Jekyll usage documentation at [jekyllrb.com](https://jekyllrb.com/)

#You can find the source code for Minima at GitHub:
#[jekyll][jekyll-organization] /
#[minima](https://github.com/jekyll/minima)

#You can find the source code for Jekyll at GitHub:
#[jekyll][jekyll-organization] /
#[jekyll](https://github.com/jekyll/jekyll)


#[jekyll-organization]: https://github.com/jekyll





# Copied from first post
#You’ll find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.

#Jekyll requires blog post files to be named according to the following format:

#`YEAR-MONTH-DAY-title.MARKUP`

#Where `YEAR` is a four-digit number, `MONTH` and `DAY` are both two-digit numbers, and `MARKUP` is the file extension representing the format used in the file. After that, include the necessary front matter. Take a look at the source for this post to get an idea about how it works.

#Jekyll also offers powerful support for code snippets:

#{% highlight ruby %}
#def print_hi(name)
#  puts "Hi, #{name}"
#end
#print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
#{% endhighlight %}

#Check out the [Jekyll docs][jekyll-docs] for more info on how to get the most out of Jekyll. File all bugs/feature requests at [Jekyll’s GitHub repo][jekyll-gh]. If you have questions, you can ask them on [Jekyll Talk][jekyll-talk].

#[jekyll-docs]: https://jekyllrb.com/docs/home
#[jekyll-gh]:   https://github.com/jekyll/jekyll
#[jekyll-talk]: https://talk.jekyllrb.com/
